### ISSUE TITLE
Issue on page /content/appendix/math.html

### ISSUE THREAD

**Issue by tuannguyen-TN** [dafriedman97/mlbook#10]
In the Math section of the Appendix, the numerator of the derivative of f(x) = g(x)/h(x) should be subtraction not addition. 
h(x).g'(x) + g(x).h'(x) => h(x).g'(x) - g(x).h'(x)

**Comment by dafriedman97** [comment]
Thanks for the catch! Fixing now.

**Comment by tuannguyen-TN** [comment]
No problem at all. In fact I hope I can ask you for more about ML since I’m
practically a newbie wanting to get started in this field. Hope we can get
along!
